### PR TITLE
fix: remove linking from profile avatar

### LINKED ISSUE #765: Can't open user menu on iPad
Tapping the avatar on iPad takes you to a user's profile, and does not open the user nav items.

https://d.pr/v/dOJTal

### PR DESCRIPTION
**Pull request by shawncothran**
Closes #765

### CODE REVIEW

**Comment by thomasthesecond** [comment]
Has this been tested? Without the avatar being an anchor, does tapping on the avatar still open the menu?

**Comment by egdelwonk** [comment]
Looks like Nick mentioned:
>lets go with the option to make the avatar always open up the menu and have a "Profile" link in the menu.

@shawncothran Does this code change still support that direction?

**Comment by shawncothran** [comment]
I did test it locally with Rizzo next linked and clicks still trigger the menu opening since I didn't change the class names.

http://d.pr/i/DcgF5X/4Htt4ZcO

**Comment by egdelwonk** [comment]
Perhaps a `<button>` instead of `<span>` if we're not going to have an `href` property?

**Comment by shawncothran** [comment]
@egdelwonk semantic. Changed to button. Tested, works on touchscreen, mobile and desktop.

**Pull request merged**
