### PR TITLE
use absolute url for header lp logo link

### PR DESCRIPTION
**Pull request by laserchicken**
request: https://github.com/lonelyplanet/rizzo-next/issues/554

### CODE REVIEW

**Comment by thomasthesecond** [comment]
Are we using https on the home page yet? I thought https was only being used for destinations next and new POIs at the moment. cc @jcreamer898

**Comment by laserchicken** [comment]
@thomasthesecond I think we support ssl for www.lonelyplanet.com domain, but I just noticed there are problems with mixed content, maybe I should use http for now. more info: https://lonelyplanet.atlassian.net/wiki/display/OPS/SSL+Planning

**Comment by laserchicken** [comment]
@thomasthesecond is this ok? Sebastian is waiting for it, I wanted to deploy it as soon as possible

**Comment by thomasthesecond** [comment]
👍

**Pull request merged**
